### ISSUE TITLE
Inner pages - Right sidebar: 'Venu menu' add file custom field at the backend of Sidebar Karaoke custom posts are not working on frontend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Hit-Studio#92]
![image](https://cloud.githubusercontent.com/assets/11186304/7223097/5aebf66a-e74e-11e4-91ac-2e97c5edd1f5.png)

**Comment by maluzynel** [comment]
Attached PDF custom fields is not working on frontend.

**Comment by christiancebudigital** [comment]
what instance that  the pdf - acf is not working... please site and example.. because in your prev bug post.. you want to limit right sidebar to show only 2 post.. and  post items are in menu order.. ive attached here a screenshot of the backend part.. anyways this is fixed..
![post](https://cloud.githubusercontent.com/assets/11186331/7314520/d7d9a414-ea97-11e4-8649-47188e7d96cf.jpg)

**Comment by maluzynel** [comment]
The custom field attach PDF file on every Sidebar Leadins custom posts are useless, unable to show on frontend Sidebar items in all inner pages.

Steps to replicate:
1. Go to Admin CMS: http://hit-studio.stage.titanweb.com.au/wp-admin
2. Scroll down and click on the 'Sidebar Leadins' custom posts to show items.
3. Click on any of the items ex. 'Contact Us'
4. Scroll down to the very bottom where you can see the 'Venue File' add file field.
5. Try to attach any file or PDF file.
6. Go back to the actual inner pages example: Hit Studio Karaoke page
7. On the Right Sidebar post items. There's no priviledge to open a PDF file attached at the backend for 'Contact Us' post.
